README.md, templates/1.0.0/Chart.yaml, templates/1.0.0/templates/_helpers.tpl, templates/1.0.0/templates/_pod.tpl, templates/1.0.0/templates/_scheduler.tpl, templates/1.0.0/templates/_volumes.tpl, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/templates/volumes.yaml, templates/1.0.0/values.yaml
The definition is not finally stable.
=> refactor application config

README.md, templates/1.0.0/templates/_pod.tpl, templates/1.0.0/templates/_scheduler.tpl, templates/1.0.0/values.yaml
* remove `lifecycle` from initContainer
* add default topologyKey `kubernetes.io/hostname`
* fix a conflict between initContainer name with container name
=> fix issues about template

README.md, templates/1.0.0/templates/volumes.yaml
1. Fix desc of dynamic volume modes in README.
- The modes should be an array rather than a string.
2. Fix a bug of PVC name.
- PVC name should be `controller name`-`volume name`.
=> Fix two minor issue about templates/1.0.0

README.md, templates/1.0.0/templates/_annotations.tpl, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/values.yaml
- Fix wrong field references of controllers.
- Add annotations to controller
- Add annotations to pod
- Remove `_config._metadata.creationTime` , `_config._metadata.source` ,`_config._metadata.class` 
- Use chart annotations now.
=> fix(templates): wrong refs of controller fields.

README.md
Dns policy now defaults to `ClusterFirst`.
=> fix(docs): dns policy now defaults to ClusterFirst

README.md, templates/1.0.0/templates/_pod.tpl
- feat(templates): remove default downward prefix
=> feat(templates): remove default downward prefix

templates/1.0.0/templates/_volumes.tpl, templates/1.0.0/templates/statefulsets.yaml
Add labels to dedicated PVCs
@zoumo
=> feat(templates): add labels to dedicated PVCs

README.md, templates/1.0.0/templates/services.yaml
- Add annotations for service
It's for unionpay. They need annotations on service to decide whether fill cluster ip to service or not.
=> feat(template): add annotations for service

Makefile
- chore(*): bump version to v1.1.0
=> chore(*): bump version to v1.1.0

stable/jenkins/2.101.0/Chart.yaml, stable/jenkins/2.101.0/values.yaml
=> fix: jenkins version 2.101 -> 2.101.0

templates/1.0.0/templates/_pod.tpl, templates/1.0.0/templates/_volumes.tpl, templates/1.0.0/templates/statefulsets.yaml
- feat(templates): support rolling update for statefulsets
- feat(template): add service account name and host path for system user
- feat(template): add host port and security context
=> Update templates to support further system features

images/galera/5.7.20/Dockerfile, images/galera/5.7.20/entrypoint.sh, images/galera/5.7.20/galera.repo, images/galera/5.7.20/mysql/conf.d/mysqld.cnf, images/galera/5.7.20/mysql/galera.cnf, images/galera/5.7.20/mysql/my.cnf, stable/galera/5.7.20/Chart.yaml, stable/galera/5.7.20/values.yaml
- feat(stable): add galera template
=> feat(stable): add galera template

stable/filemanager/1.4.4/description.yaml, stable/galera/5.7.20/description.yaml, stable/influxdb/1.4.2/description.yaml, stable/mariadb/10.2.12/description.yaml, stable/mongo/3.6.1/description.yaml, stable/mysql/5.7.20/description.yaml, stable/redmine/3.4.4/description.yaml, stable/wordpress/4.9.1/description.yaml
=> Add descriptions for charts

stable/gitlab-ce/10.3.3/description.yaml, stable/jenkins/2.101.0/description.yaml, stable/memcached/1.5.4/description.yaml, stable/nginx/1.13.8/description.yaml, stable/rabbitmq/3.7.2/description.yaml, stable/redis/4.0.6/description.yaml
=> docs: add description for charts

build/charts/build.sh
- feat(build): clear output dir in building
=> feat(build): clear output dir in building

stable/redis/4.0.6/values.yaml
=> fix: switch redis requests and limits resources

templates/1.0.0/templates/_pod.tpl
fix(templates): update gpu resource key
In Kubernetes 1.8, GPU resource key should be `nvidia.com/gpu`.
/assign @yejiayu 
```release-note
Update GPU resource key
```
=> fix(templates): update gpu resource key

stable/filemanager/1.4.4/values.yaml, stable/galera/5.7.20/values.yaml, stable/gitlab-ce/10.3.3/values.yaml, stable/influxdb/1.4.2/values.yaml, stable/jenkins/2.101.0/values.yaml, stable/mariadb/10.2.12/values.yaml, stable/memcached/1.5.4/values.yaml, stable/mongo/3.6.1/values.yaml, stable/mysql/5.7.20/values.yaml, stable/nginx/1.13.8/values.yaml, stable/rabbitmq/3.7.2/values.yaml, stable/redmine/3.4.4/values.yaml, stable/wordpress/4.9.1/values.yaml
- replace blankspace with number for service-nodeport
Fixes https://github.com/caicloud/quality/issues/318
/cc @zoumo 
```release-note
NONE
```
=> fix(nodePort): replace blankspace with number for service-nodeport

templates/1.0.0/templates/_scheduler.tpl, templates/1.0.0/templates/cronjobs.yaml
Fixes #
```release-note
NONE
```
=> fix(template): fix template issues of cronjob and schedule

templates/1.0.0/templates/daemonsets.yaml
Fixes #
/cc @zoumo 
```release-note
NONE
```
=> fix(template): correct daemonset updateStrategy

templates/1.0.0/templates/_pod.tpl, templates/1.0.0/templates/_scheduler.tpl, templates/1.0.0/templates/_volumes.tpl, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/templates/volumes.yaml
Fixes #
/cc @zoumo 
```release-note
NONE
```
=> feat(template): add quote for all string fields

README.md, templates/1.0.0/templates/_volumes.tpl, templates/1.0.0/templates/configmaps.yaml, templates/1.0.0/templates/secrets.yaml, templates/1.0.0/values.yaml
Add configs and secrets
Fixes #
/cc @zoumo 
```release-note
NONE
```
=> feat(*): add configs and secrets

Makefile, build/charts/test.sh, build/templates/Dockerfile, build/templates/build.sh, build/templates/test.sh
Fixes #
```release-note
feat: add templates image
```
=> feat: add templates image

templates/1.0.0/templates/_labels.tpl, templates/1.0.0/templates/configmaps.yaml, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/secrets.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/templates/volumes.yaml
Fixes #
```release-note
fix: selector must match labels in template
```
=> fix: selector must match labels in template

README.md
Move privileged and capabilities into securityContext
Fixes #
/cc @zoumo 
```release-note
NONE
```
=> fix(readme): move privileged and capabilities into securityContext

templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/jobs.yaml
Fixes https://github.com/caicloud/pangolin/issues/192
/cc @kdada @bbbmj 
```release-note
NONE
```
=> fix: remove selectors from templates for cronjobs and jobs

OWNERS
Fixes #
Reference to #
/cc @zoumo
```release-note
NONE
```
=> chore(OWNERS): add li-ang to OWNERS

README.md
Fixes #
Reference to #
```release-note
NONE
```
=> fix(readme): correct HTTP and TCP probe doc

README.md
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix(readme): correct field values in schedule

images/filemanager/1.4.4/Docker.json, images/filemanager/1.4.4/Dockerfile, images/filemanager/1.4.4/README.md
`release/filemanger:1.4.4` 中有 `sh` 命令 `library/filemanger:1.4.4` 中没有。
Reference to https://github.com/caicloud/quality/issues/275
/cc @zoumo @kdada 
```release-note
NONE
```
=> fix(filemanager): use new filemanger image

Makefile
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.5

stable/mongo/3.6.1/description.yaml, stable/mongo/3.6.1/values.yaml
Fixes #
Reference to https://github.com/caicloud/quality/issues/1249
/cc @zjj2wry @zoumo 
```release-note
NONE
```
=> fix(mongo): modify mongo volume

README.md, templates/1.0.0/templates/_pod.tpl
fix(mount): add mountPropagation field for Container.volumeMounts
Fixes #
Reference to https://github.com/caicloud/infra/issues/223
/cc @zoumo 
```release-note
NONE
```
=> fix(mount): add mountPropagation field for Container.volumeMounts

Makefile
chore(docs): update VERSION to v1.2.7
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.7

README.md, templates/1.0.0/templates/_volumes.tpl
Fixes #
Reference to #
```release-note
NONE
```
=> feat(tmpl): support glusterfs

Makefile
chore(docs): update VERSION to v1.2.8
Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.8

CODEOWNERS, OWNERS
chore(*): modify OWNERS & CODEOWNERS
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> chore(*): modify OWNERS & CODEOWNERS

README.md
docs(*): update README.md
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> docs(*): update README.md

templates/1.0.0/templates/_pod.tpl
fix(hostAliases): add hostAliases for pod
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix(hostAliases): add hostAliases for pod template

templates/1.0.0/templates/statefulsets.yaml
fix(statefulset): support OnDelete updsateStrateg for statefulse
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix(statefulset): support OnDelete updsateStrateg for statefulset

templates/1.0.0/templates/_pod.tpl
fix(runAsNonRoot): add runAsNonRoot for pod template
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=>  fix(runAsNonRoot): add runAsNonRoot for pod template

Makefile
chore(docs): update VERSION to v1.2.9
Fixes #
Reference to #
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.9

templates/1.0.0/templates/statefulsets.yaml
fix(statefulset): add statefulset service default port
Fixes #
Reference to #
```release-note
NONE
```
=> fix(statefulset): add statefulset service default port

Makefile
chore(docs): update VERSION to v1.2.10
Fixes #
Reference to #
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.10

stable/eureka/1.9.2/Chart.yaml, stable/eureka/1.9.2/description.yaml, stable/eureka/1.9.2/values.yaml, stable/hystrix-dashboard/1.5.12/Chart.yaml, stable/hystrix-dashboard/1.5.12/description.yaml, stable/hystrix-dashboard/1.5.12/values.yaml, stable/zipkin/2.9.3/Chart.yaml, stable/zipkin/2.9.3/description.yaml, stable/zipkin/2.9.3/values.yaml
feat(microservice): add eureka, hystrix-dashboard and zipkin
Fixes #
Reference to #
/cc @stonesfour 
```release-note
NONE
```
=> feat(microservice): add eureka, hystrix-dashboard and zipkin

Makefile
chore(docs): update VERSION to v1.2.11
Fixes #
Reference to #
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.11

stable/filemanager/1.4.4/values.yaml
fix(filemanager): fix filemanager image
Fixes #
Reference to #
```release-note
NONE
```
=> fix(filemanager): fix filemanager image

stable/mysql/5.7.20/values.yaml, stable/rabbitmq/3.7.2/values.yaml
fix(statefulset): fix mysql & rabbitmq config
Fixes #
Reference to #
```release-note
NONE
```
=> fix(statefulset): fix mysql & rabbitmq config

Makefile
chore(docs): update VERSION to v1.2.12
Fixes #
Reference to #
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.12

README.md
docs(*): fix HTTP probe handler description
Fixes #
Reference to https://github.com/caicloud/quality/issues/1581
```release-note
NONE
```
=> docs(*): fix HTTP probe handler description

README.md, templates/1.0.0/templates/statefulsets.yaml
fix(stateful): modify statefulset podManagementPolicy
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix(stateful): fix statefulset podManagementPolicy

Makefile
chore(docs): update VERSION to v1.2.13
Fixes #
Reference to #
/cc @zoumo  @whalecold 
```release-note
NONE
```
=> chore(docs): update VERSION to v1.2.13

templates/1.0.0/templates/statefulsets.yaml
Revert "fix(statefulset): add statefulset service default port (#83)"
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> Revert "fix(statefulset): add statefulset service default port (#83)"

stable/hystrix-dashboard/1.5.12/description.yaml, stable/hystrix-dashboard/1.5.12/values.yaml
fix(microservice): modify hystrix-dashboard image
Fixes #
Reference to https://github.com/caicloud/quality/issues/1631
/cc @zoumo 
```release-note
NONE
```
=> fix(microservice): modify hystrix-dashboard image

stable/zipkin/2.9.3/description.yaml, stable/zipkin/2.9.3/values.yaml
fix(zipkin): modify zipkin request quota & service port
Fixes #
Reference to https://github.com/caicloud/quality/issues/1631
/cc @zoumo  @whalecold 
```release-note
NONE
```
=> fix(zipkin): modify zipkin request quota & service port

stable/eureka/1.9.2/description.yaml, stable/eureka/1.9.2/values.yaml
fix(eureka): modify eureka request quota
Fixes #
Reference to #
/cc @zoumo @whalecold 
```release-note
NONE
```
=> fix(eureka): modify eureka request quota

README.md, stable/filemanager/1.4.4/values.yaml, stable/galera/5.7.20/values.yaml, stable/gitlab-ce/10.3.3/values.yaml, stable/influxdb/1.4.2/values.yaml, stable/jenkins/2.101.0/values.yaml, stable/mariadb/10.2.12/values.yaml, stable/memcached/1.5.4/values.yaml, stable/mongo/3.6.1/values.yaml, stable/mysql/5.7.20/values.yaml, stable/nginx/1.13.8/values.yaml, stable/rabbitmq/3.7.2/values.yaml, stable/redmine/3.4.4/values.yaml, stable/wordpress/4.9.1/values.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/values.yaml
Fixes #
Reference to #
```release-note
NONE
```
=> feat: delete service export

Makefile
Fixes #
Reference to #
```release-note
NONE
```
=> build: bump up version to v1.2.14

stable/filemanager/1.4.4/values.yaml, stable/galera/5.7.20/values.yaml, stable/gitlab-ce/10.3.3/values.yaml, stable/influxdb/1.4.2/values.yaml, stable/jenkins/2.101.0/values.yaml, stable/mariadb/10.2.12/values.yaml, stable/memcached/1.5.4/values.yaml, stable/mongo/3.6.1/values.yaml, stable/mysql/5.7.20/values.yaml, stable/nginx/1.13.8/values.yaml, stable/rabbitmq/3.7.2/values.yaml, stable/redis/4.0.6/description.yaml, stable/redis/4.0.6/values.yaml, stable/redmine/3.4.4/values.yaml, stable/wordpress/4.9.1/values.yaml
Fixes #
Reference to https://github.com/caicloud/quality/issues/1779 https://github.com/caicloud/quality/issues/1799
```release-note
fix(stable): modify the charts so that it matches the description
```
=> fix(stable): modify the charts so that they matche the description

templates/1.0.0/templates/services.yaml
feat(label): add services labels
Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```
=> feat(label): add services labels

README.md
chore(readme): update readme.md
Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```
=> chore(readme): update readme.md

stable/redis/4.0.6/values.yaml
fix(protocol): modify redis protocol
Fixes #
Reference to #https://github.com/caicloud/quality/issues/1833#issuecomment-442000981
/cc @li-ang 
```release-note
NONE
```
=> fix(protocol): modify redis protocol

stable/config-server/2.0.0/values.yaml, stable/eureka/2.0.0/values.yaml, stable/hystrix-dashboard/1.2.3/values.yaml, stable/turbine/2.0.0/values.yaml, stable/zipkin/2.11.8/values.yaml, stable/zuul/2.0.0/values.yaml
feat(microservice): change the default access type
Fixes #
Reference to #
/cc @li-ang @stonesfour 
```release-note
springcloud组件默认都用nodeport方式接入
```
=> feat(microservice): change the default access type

Makefile, README.md, stable/rabbitmq/3.7.2/values.yaml, templates/1.0.0/templates/deployments.yaml
Fixes #
Reference to https://github.com/caicloud/quality/issues/1335
```release-note
NONE
```
=> feat: support Recreate strategy in deployment

Makefile, templates/1.0.0/templates/statefulsets.yaml
fix(statefulset): fix statefulset pod template labels
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix(statefulset): fix statefulset pod template labels

stable/filemanager/1.4.4/values.yaml, stable/gitlab-ce/10.3.3/values.yaml, stable/influxdb/1.4.2/values.yaml, stable/jenkins/2.101.0/values.yaml, stable/mariadb/10.2.12/values.yaml, stable/mongo/3.6.1/values.yaml, stable/mysql/5.7.20/values.yaml, stable/redis/4.0.6/values.yaml
fix(mount): transform mount type from Scratch to Static
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix(mount): transform mount type from Scratch to Static

Makefile
chore(version): update version
Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```
=> chore(version): update version

Makefile, README.md, templates/1.0.0/templates/_pod.tpl
feat: add ExtendedResourceClaims for container
基于 v1.2.14(compass v2.7.2) 做出的更改，不影响已有功能，可以向后兼容
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> feat: add ExtendedResourceClaims for container

Makefile, README.md, templates/1.0.0/templates/_scheduler.tpl
fix: remove "schedule.caicloud.io/" prefix for scheduler label
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix: remove "schedule.caicloud.io/" prefix for schedule label

README.md, templates/1.0.0/templates/services.yaml
fix: correct service selector
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> [CPS-464] fix: correct service selector

README.md, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/statefulsets.yaml
feat(controller): support to set controller name
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> [CPS-473] feat(controller): support to set controller name

README.md, templates/1.0.0/templates/_pod.tpl
feat(resource): add localstorage resource
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> [CPS-494] feat(resource): add localstorage resource

Makefile, README.md
chore: rename caicloud.io/localstorage to caicloud.io/local-storage
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> [CPS-494] chore: rename caicloud.io/localstorage to caicloud.io/local-storage

Makefile
chore(docs): update VERSION to v1.3.0
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> chore(docs): update VERSION to v1.3.0

README.md
chore(docs): fix docs error
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> chore(docs): fix docs error

README.md, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/statefulsets.yaml
feat(controller): support to set controller name
cherrypick from https://github.com/caicloud/charts/pull/150
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> [CPS-187] feat(controller): support to set controller name

Makefile, templates/1.0.0/templates/_helpers.tpl, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/templates/volumes.yaml
fix: add onlyname function
fix: modify controllerName genration function
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> [CPS-487] fix: use fullname to generate all controllers' controllerName

Makefile, templates/1.0.0/templates/_helpers.tpl, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/templates/volumes.yaml
cherrypick #162 
fix: add onlyname function
fix: modify controllerName genration function
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> [CPS-473] fix: use fullname to generate all controllers' controllerName

Makefile, templates/1.0.0/templates/_helpers.tpl, templates/1.0.0/templates/_labels.tpl, templates/1.0.0/templates/configmaps.yaml, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/secrets.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/values.yaml
Fixes #
Reference to #
/cc @li-ang @whalecold 
```release-note
NONE
```
=> feat: add app and version labels for canary

README.md, templates/1.0.0/templates/_pod.tpl
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> feat(priority): add support for pod priority

templates/1.0.0/values.yaml
fix: add hostAliases into pod
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
=> fix: add hostAliases into pod

templates/1.0.0/templates/services.yaml
Fixes [【星巴克-郭辉】支持设置deployment的lable](https://github.com/caicloud/prod-issue/issues/649)
Reference to #
```release-note
NONE
```
=> feat(service): custom selector for service

build/charts/build.sh, build/charts/test.sh
fix(script): update build script
Fixes #
Reference to #
/cc @zxq-bit 
```release-note
NONE
```
=> fix(script): update build script

templates/1.0.0/templates/_scheduler.tpl, templates/1.0.0/templates/services.yaml
Fixes [【星巴克-郭辉】支持设置deployment的lable](https://github.com/caicloud/prod-issue/issues/649)
Reference to #
```release-note
NONE
```
=> adapt compass 2.8.x

build/charts/Dockerfile, build/charts/build.sh, stable/release/elasticsearch/6.5.4/values.yaml, stable/release/kibana/6.5.4/values.yaml
fix(release): add es initcontainer resource
Fixes #
Reference to #
```release-note
NONE
```
=> [CPS-2423] fix(release): add es initcontainer resource

README.md, templates/1.0.0/templates/_pod.tpl, templates/1.0.0/values.yaml
feat(wanda): add dns config into pod's template
Fixes #
Reference to #
```release-note
NONE
```
=> feat(wanda): add dns config into pod's template

README.md, templates/1.0.0/templates/services.yaml, templates/1.0.0/values.yaml
feat(sessionAffinity): add service session affinity
Fixes #
Reference to #
/cc @hezhizhen @zxq-bit 
```release-note
NONE
```
=> feat(sessionAffinity): add service session affinity

templates/1.0.0/templates/daemonsets.yaml
fix(type): add daemonset updateStrategy type
Fixes #
Reference to #
```release-note
NONE
```
=> [CPS-2559] fix(type): add daemonset updateStrategy type

stable/release/elasticsearch/6.5.4/values.yaml
fix(version): modify es image version
Fixes #
Reference to #
/cc @hezhizhen @zxq-bit 
```release-note
NONE
```
=> fix(version): modify es image version

stable/release/elasticsearch/6.5.4/values.yaml, stable/release/kibana/6.5.4/values.yaml
fix(image): correct images
Fixes #
Reference to #
/cc @zxq-bit @hezhizhen 
```release-note
NONE
```
=> fix(image): correct images

Makefile, stable/release/elasticsearch/6.5.4/values.yaml
Fixes #
Reference to #
```release-note
NONE
```
=> [CPS-2423] fix(volume): es uses dedicated type volume

Makefile, README.md, templates/1.0.0/templates/_helpers.tpl, templates/1.0.0/templates/_labels.tpl, templates/1.0.0/templates/_pod.tpl, templates/1.0.0/templates/_scheduler.tpl, templates/1.0.0/templates/configmaps.yaml, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/secrets.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/templates/volumes.yaml, templates/1.0.0/values.yaml
cherry-pick from v1.2.20 to v1.3.2
Fixes #
Reference to #
/hold
```release-note
NONE
```
=> feat(wanda): cherry-pick to v1.3.2

Makefile, templates/1.0.0/templates/services.yaml
feat(*): custom selector for service
Fixes #
Reference to #
/cc @zxq-bit 
```release-note
NONE
```
=> feat(*): custom selector for service

Makefile, templates/1.0.0/templates/services.yaml
Fixes #
Reference to #
```release-note
NONE
```
=> fix(*): keep same with standard

README.md, templates/1.0.0/values.yaml
Fixes #
Reference to #
/cc @zxq-bit @hezhizhen 
```release-note
NONE
```
=> feat(toleration): add toleration to pod template

stable/release/kibana/6.5.4/values.yaml
[CPS-4689]fix(protocol): use http protocol instead of tcp
Fixes #
Reference to #
/cc @hezhizhen
```release-note
NONE
```
=> [CPS-4689]fix(protocol): use http protocol instead of tcp

Makefile, README.md, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/jobs.yaml
Fixes #
Reference to #
```release-note
NONE
```
=> feat: add backoffLimit for job and cronjob

Makefile, build/charts/Dockerfile, build/charts/test.sh, build/templates/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
=> chore:change base image and cargo addr

Makefile, build/charts/Dockerfile, build/charts/Dockerfile.arm64, build/templates/Dockerfile.arm64
Fixes #
Reference to http://jira.caicloud.xyz/browse/CPS-5956
/cc @hezhizhen @whalecold 
```release-note
NONE
```
=> feat(*): support arm64

Makefile, build/charts/Dockerfile.arm64, build/templates/Dockerfile.arm64
Backport from master:
* chore(build): fix Makefile and registry
* chore(build): support arm64v8
* chore(build): fix Makefile
Fixes #
Reference to 
- #211
- http://jira.caicloud.xyz/browse/CPS-5956
/cc @whalecold @hezhizhen @liwandaniel 
```release-note
NONE
```
=> [release-1.3] feat(*): support arm64 (#211)

README.md, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/jobs.yaml
* feat: add backoffLimit for job and cronjob
* chore: update README file
* delete useless navigate
* fix default number
* bump version to 1.3.4
* chore
Fixes #
Reference to #
/cc @hezhizhen @qianlei90
```release-note
NONE
```
=> feat: add backoffLimit for job and cronjob (#203)

OWNERS
Fixes #
Reference to #
/cc @whalecold @hezhizhen 
```release-note
NONE
```
=> chore(owner): change owner

stable/release/kibana/6.5.4/values.yaml
Fixes #
Reference to #
```release-note
NONE
```
=> [CPS-6722]fix(kibana): correct kibana image

stable/release/elasticsearch/6.5.4/values.yaml
Fixes #
Reference to #
/cc @qianlei90 @hezhizhen 
```release-note
NONE
```
=> [CPS-6758]fix(elasticsearch): correct elasticsearch image

templates/1.0.0/templates/services.yaml
Fixes #
Reference to #
- [JIRA](http://jira.caicloud.xyz/browse/BEST-73)
- [设计文档](https://docs.google.com/document/d/1ZIu_zh7Zier92rAPWEuwQJmljwA11X_NPiBYAQlTXkY/edit#heading=h.ya7pnmlqeft2)
```release-note
NONE
```
=> [BEST-73]remove default service selector

Makefile, build/charts/Dockerfile
charts 构建镜像时需要联网，为了无网构建，将需要联网部分的构建操作放到 base 镜像中。
Fixes #
Reference to 
- JIRA: http://jira.caicloud.xyz/browse/CPS-7403
- dockerfile: https://github.com/caicloud/dockerfile-release/pull/119
```release-note
NONE
```
=> [CPS-7403] chore(*): use base image to build

Makefile, build/charts/Dockerfile
Backport #222 to release-1.4
Fixes #
Reference to #
```release-note
NONE
```
=> chore(*): use base image debian:stretch-ruby (#222)

Makefile, README.md, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/jobs.yaml
Fixes #
Reference to # https://github.com/caicloud/charts/pull/213
/cc @qianlei90 @hezhizhen 
```release-note
NONE
```
=> [CPS-7378] feat: add backoffLimit for job and cronjob 

build/templates/Dockerfile
Fixes #
Reference to #
```release-note
NONE
```
=> fix basic image

Makefile, build/charts/Dockerfile
backport #222 to release-1.3 branch
Fixes #
Reference to #
```release-note
NONE
```
=> chore(*): use base image debian:stretch-ruby (#222) (#223)

README.md, templates/1.0.0/templates/_pod.tpl, templates/1.0.0/values.yaml
backport #181 to branch cps-2.8.5/wanda
Fixes #
Reference to http://jira.caicloud.xyz/browse/WANDA-74
/cc @whalecold @moshuipan 
```release-note
NONE
```
=> [WANDA-74] feat(wanda): add dns config into pod's template (#181)

Makefile, build/charts/Dockerfile, build/charts/test.sh, build/templates/Dockerfile, stable/release/eureka-cluster/2.0.0/Chart.yaml, stable/release/eureka-cluster/2.0.0/description.yaml, stable/release/eureka-cluster/2.0.0/values.yaml
feat(release): add eureka cluster release in application store
Fixes #
Reference to 
/cc @whalecold @hezhizhen @quasimodo7614 
```release-note
NONE
```
=> [PAPER-63]feat(release): add eureka cluster release in application store

stable/release/jenkins-cluster/2.101.0/Chart.yaml, stable/release/jenkins-cluster/2.101.0/description.yaml, stable/release/jenkins-cluster/2.101.0/values.yaml, stable/release/jenkins/2.101.0/description.yaml, stable/release/mongo-cluster/3.4.1/Chart.yaml, stable/release/mongo-cluster/3.4.1/description.yaml, stable/release/mongo-cluster/3.4.1/values.yaml, stable/release/nginx-cluster/1.13.8/Chart.yaml, stable/release/nginx-cluster/1.13.8/description.yaml, stable/release/nginx-cluster/1.13.8/values.yaml, stable/release/rabbitmq-cluster/3.8.1/Chart.yaml, stable/release/rabbitmq-cluster/3.8.1/description.yaml, stable/release/rabbitmq-cluster/3.8.1/values.yaml, stable/release/redis-cluster/4.0.6/Chart.yaml, stable/release/redis-cluster/4.0.6/description.yaml, stable/release/redis-cluster/4.0.6/values.yaml, stable/release/redis/4.0.6/description.yaml
feat(release): add mongo,redis,rabbitmq,jenkins,nginx cluster
Fixes #
Reference to #
/cc @whalecold @hezhizhen @FogDong 
```release-note
NONE
```
=> [PAPER-63]feat(release): add mongo,redis,rabbitmq,jenkins,nginx cluster

stable/release/kibana/6.5.4/values.yaml
Fixes #
Reference to #
/cc @FogDong
```release-note
NONE
```
=> fix(kibana): use appropriate es URL

stable/release/mongo-cluster/3.4.1/values.yaml, stable/release/rabbitmq-cluster/3.8.1/description.yaml, stable/release/rabbitmq-cluster/3.8.1/values.yaml
fix mongo chart file 
Fixes #
Reference to #
/cc @whalecold @hezhizhen @FogDong 
```release-note
NONE
```
=> Fix: mongo cluster's chart file 's wrong format, add some description

stable/release/rabbitmq-cluster/3.8.1/values.yaml
fix rabbitmq-cluster's cpu limit less than request
Fixes #
Reference to #
/cc @whalecold @hezhizhen @FogDong 
```release-note
NONE
```
=> FIX(rabbitmq-cluster): cpu's limit must larger than request

stable/release/config-server-cluster/2.0.0/values.yaml, stable/release/influxdb-cluster/1.8.1/description.yaml, stable/release/influxdb-cluster/1.8.1/values.yaml, stable/release/redmine-cluster/4.1.1/description.yaml, stable/release/redmine-cluster/4.1.1/values.yaml
fix(release): add default env for influxdb and config server
Fixes #
Reference to #
/cc @whalecold @quasimodo7614 
```release-note
NONE
```
=> [PAPER-106]fix(release): add default env for influxdb and config server

templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/services.yaml
fix(charts):fix deployment template
Fixes #
Reference to #
/cc @wzqnls @hezhizhen @qianlei90 @whalecold 
```release-note
NONE
```
=> [BEST-255]fix(charts):fix deployment template

Makefile, build/charts/Dockerfile, build/charts/test.sh, build/templates/Dockerfile, templates/1.0.0/templates/_pod.tpl
add nameservers for pod
Fixes #
Reference to #
/cc @moshuipan 
```release-note
NONE
```
=> feat(dnsConfig): add nameservers

templates/1.0.0/templates/_labels.tpl, templates/1.0.0/templates/configmaps.yaml, templates/1.0.0/templates/cronjobs.yaml, templates/1.0.0/templates/daemonsets.yaml, templates/1.0.0/templates/deployments.yaml, templates/1.0.0/templates/jobs.yaml, templates/1.0.0/templates/secrets.yaml, templates/1.0.0/templates/services.yaml, templates/1.0.0/templates/statefulsets.yaml, templates/1.0.0/templates/volumes.yaml, templates/1.0.0/values.yaml
添加项目和组件的标签
Fixes #
Reference to #
/cc @moshuipan 
```release-note
NONE
```
=> feat(project): add project and component  label
